#!/bin/bash

: ${LOGFILE:=/tmp/ambari_consul_reset.log}
: ${DEBUG:=1}

main(){
  debug "$(date) ambari reset event triggered."
  ambari-server stop
  PGPASSWORD=bigdata psql -h $POSTGRES_DB -U ambari postgres < /var/lib/ambari-server/resources/Ambari-DDL-Postgres-CREATE.sql
  ambari-server start
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
