#!/bin/bash

: ${LOGFILE:=/tmp/ambari_consul_start.log}
: ${DEBUG:=1}

main(){
  debug "$(date) ambari agent start event triggered."
  ambari-agent status
  if [ $? -eq 0 ]; then
      debug "Ambari agent already running."
  else
      debug "Ambari agent starting..."
      ambari-agent start -v
  fi
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
