[plugin]
name = "ambari-restart"
description = "Restart ambari agents"
version = "1.0"
maintainer_name = "SequenceIQ"
maintainer_email = "info@sequenceiq.com"
website_url = "http://github.com/sequenceiq/consul-plugins-ambari-restart"

[plugin.config]

[plugin.compatibility]
